# Page settings
baseurl = "localhost:1313"
title = "Rechtsberatung Heinz Walser - pat. Rechtsagent"
languageCode = "de-ch"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Heinz Walser"
  description = "Rechtsberatung Walser"
  email = "info@rb-walser.ch"
  


  # Navigation
  [params.navigation]
    brand = "Rechtsberatung"
    brandSub = "<div id='logo-sub'>Heinz Walser&nbsp;&nbsp;&nbsp;pat. Rechtsagent</div>"
    home = "Willkommen"
    services = "Fachgebiete"
    contact = "Kontakt"
    about = "Über mich"
    links = "Links"

  
  # Hero section
  [params.hero]
    title = "Ihr Partner für Rechtsfragen"
    subtitle = 'Haben Sie rechtliche Probleme? Fühlen Sie sich ungerecht behandelt?<br /><div class="subtitle-address"><div id="srv-text">Heinz Walser<br />pat. Rechtsagent<br />Amatännenstrasse 9<br />8882 Unterterzen<br />Tel. 079 318 11 31</div><div id="srv-logo"></div></div>'
 


  [[params.intro.item]]
    title = "Beratung"
    description = "Als pat. Rechtsagent mit über 30 Jahren Erfahrung als Rechtsberater und Tätigkeit in der öffentlichen Verwaltung berate ich Sie in alltäglichen Fragen kompetent und umfassend. Rufen Sie an."
    icon = "icon-user"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Mandate"
    description = "Selbstverständlich übernehme ich auch Mandate in Ihrem Auftrag. Wenn immer möglich, steht für mich in streitigen Fällen eine aussergerichtliche Lösung mit der Gegenpartei im Vordergrund."
    icon = "icon-archive"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Behörden"
    description = "Ich berate Sie auch im Umgang mit den Behörden. Ich biete Ihnen Hilfe bei Einsprachen und Stellungnahmen an. Ich schreibe die Eingaben für Sie oder trete je nach Wunsch in Kontakt mit der Behörde."
    icon = "icon-institution"
    img = "img_10.jpg"




  # Services section
  [params.services]
    enable = true
    title = "Fachgebiete"
    description = "Stark in allen Bereichen"

    [[params.services.item]]
      title = "Ehe- &amp; Erbrecht"
      description = "<ul><li>Beratung für die Ausarbeitung von Ehe- und Erbverträgen</li><li>Willensvollstrecker- und Erbenvertretermandate</li><li>Durchführung von Erbteilungen</li><li>Allgemeine Hilfeleistungen bei Todesfällen für die administrativen Belange</li><li>Beratung in der Ausarbeitung von Testamenten</li></ul>"
      icon = "icon-cubes"

    [[params.services.item]]
      title = "Allgemeines"
      description = "<ul><li>Personenrecht einschl. Namensänderungsverfahren</li><li>Eheschliessungsverfahren</li><li>Kindesrecht einschl. Adoption</li><li>Nachbarrecht</li><li>Zivilprozessrecht</li><li>und Weiteres</li></ul>"
      icon = "icon-legal"

    [[params.services.item]]
      title = "Vorsorgeauftrag"
      description = "<ul><li>Beratung in der Ausarbeitung von Vorsorgeaufträgen (Bestimmung einer Person für die Vertretung bei eintretender Urteilsunfähigkeit)</li></ul>"
      icon = "icon-money"

    [[params.services.item]]
      title = "Scheidung &amp; Trennung"
      description = "<ul><li>Beratung im Zusammenhang mit einer Scheidung oder Trennung inklusive Abfassung von Trennungsvereinbarungen und Scheidungskonventionen</li></ul>"      
      icon = "icon-venus-mars"

    [[params.services.item]]
      title = "Vertragsrecht"
      description = "<ul><li>Ausarbeitung von Verträgen und Überprüfung (Kauf-, Miet- Arbeits- und Darlehensverträge usw.)</li></ul>"
      icon = "icon-contract"

    [[params.services.item]]
      title = "SchKG"
      description = "<ul><li>Interessenwahrung im Verfahren der Schuldbetreibung und Konkurs</li></ul>"      
      icon = "icon-unlink"


    [[params.services.item]]
      title = "Steuerrecht"
      description = "<ul><li>Ausfüllen der jährlichen Steuererklärung(Einkommens- und Vermögenssteuer) mit allfälligen Einspracheverfahren</li><li>Grundstückgewinnsteuer</li><li>Erbschafts- und Schenkungssteuer</li></ul>"
      icon = "icon-database"

    [[params.services.item]]
      title = "Verwaltungsverfahren"
      description = "<ul><li>Eingaben an Verwaltung und Behörden jeglicher Art</li><li>Durchführung von Rechtsmittelverfahren</li></ul>"      
      icon = "icon-institution"



  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Treten Sie in Kontakt"
    description = "Für ein unverbindliches Gespräch stehe ich gerne zur Verfügung."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Walser Heinz<br />Amatännenstrasse 9, 8882 Unterterzen"],
        ["icon-phone", "079 318 11 31"],
        ["icon-envelope", "<a href=\"\" class=\"mailto\"></a>"],
        ["icon-globe", "<a href=\"https://www.rb-walser.ch\">www.rb-walser.ch</a>"]
      ]

    name = "Name"
    email = "Email"
    phone = "Telefon"
    message = "Nachricht"
    button = "Senden"




  # About section
  [params.about]
    enable = true
    title = "Über mich"
    description = "<img class=\"about\" src=\"/images/about.jpg\"><br /><br />Ich habe über 40 Jahre Verwaltungserfahrung auf Stufe Gemeinde und Kanton mit langjähriger Praxis    im Personenrecht, Eheschliessungsverfahren, im Ehescheidungs- und Ehetrennungsverfahren, im Güter- und Erbrecht als auch im Schuldbetreibungs- und Konkursrecht, Steuer- sowie Zivilprozessrecht. Aber auch im Arbeitsrecht, in Mietstreitigkeiten sowie im allgemeinen Vertragsrecht habe ich mir entsprechende Fachkompetenzen aneignen können.<br /><br />Im Jahr 1977 habe ich das Patent als Rechtsagent erworben. Im Rahmen meiner langjährigen Tätigkeit als Rechtsberater bei der Beratungsstelle für Familien in St.Gallen bis 2014 konnte ich wertvolle Erfahrungen im Beratungsbereich sammeln.<br /><br />Seit 2015 habe ich meine Tätigkeit beim Departement des Innern des Kantons St.Gallen als Amtsleiter aufgegeben und biete nun eine zielführende und lösungsorientierte Rechtsberatung als Rechtsagent auf selbständiger Basis an."



  # About section
  [params.links]
    enable = true
    title = "Wichtige Adressen"
    description = "<ul> <li><a href='https://www.admin.ch/gov/de/start/bundesrecht/systematische-sammlung.html'>Systematische Sammlung des Bundesrechts</a></li> <li><a href='http://www.bger.ch/'>Bundesgerichtsentscheide</a></li> <li><a href='https://www.gesetzessammlung.sg.ch/'>St. Gallische Gesetzesammlung</a></li> <li><a href='http://www.sg.ch/home/publikationen___services/publikationen/gerichts--und-verwaltungspraxis.html'>St. Gallische Gerichts- und Verwaltungspraxis</a></li> <li><a href='http://jusletter.weblaw.ch/juslissues/2017/875.html'>Juristische online-Zeitschrift Schweiz</a></li> <li><a href='http://www.gerichte.sg.ch/'>Gerichte des Kantons St. Gallen</a></li> <li><a href='http://www.afhn.sg.ch/'>Amtsnotariate des Kantons St. Gallen</a></li> <li><a href='http://www.zefix.ch/'>Handelsregister</a></li> <li><a href='http://www.sav-fsa.ch/'>Schweizerischer Anwaltsverband</a></li> <li><a href='https://www.anwaltsverbandsg.ch/'>St. Gallischer Anwaltsverband</a></li> <li><a href='http://www.rechtsagentenverband.ch/'>St. Gallischer Rechtsagentenverband</a></li> <li><a href='http://www.steuern.sg.ch/'>Steueramt des Kantons St. Gallen</a></li> <li><a href='http://steuerrevue.ch/'>Fachzeitschrift für Steuerwesen</a></li> </ul>"





  # Footer section
  [params.footer]
    enable = true
    copyright = '<br />&copy; Heinz Walser. Alle Rechte vorbehalten.
    <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <br />
    Images: <a href="http://pexels.com/" target="_blank">Pexels</a>,
    <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>
    Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
